name: First workflow
on: workflow-dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "Hello World"
      - name: print bye
        run: echo "Done bye"
        
